name: 'student-grade-predictor'
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.13
  - pip
  - ipykernel
  - nb_conda_kernels
  - altair-all=5.4.*
  - vega_datasets
  - scipy
  - matplotlib>=3.2.2
  - scikit-learn
  - requests>=2.24.0
  - eli5
  - jinja2
  - pip:
    - altair_ally>=0.1.1
